### PR TITLE
Make it work with TypeScript 2.9

### PR DESCRIPTION
**Pull request by karol-majewski**
TypeScript 2.9 infers the result of calling `keyof` operator as `string | number | symbol`. Disabling the new behaviour by switching a flag in `tsconfig.json` solves the problem within the project, but not fot the library consumers.

I just tested it locally with `npm link` and it seems to be working fine.

### CODE REVIEW

**Comment by henrikra** [comment]
Hmm should you use `Extract` like the blog post says?

**Comment by karol-majewski** [comment]
I couldn't get it to work because of these:

image

**Comment by henrikra** [comment]
@rawrmaan Could you also review this pr?

**Comment by rawrmaan** [comment]
Closing in favor of #9. Sorry for the wait everyone!

**Comment by rawrmaan** [comment]
Released on npm as `2.0.0`.

**Pull request closed without merging**
